### ISSUE TITLE
Render cloth on video

### ISSUE THREAD

**Issue by hungnguyen2611** [tomguluson92/cloth2tex#1]
Great work! I was impressed by the result in the Real people Try-on section. How do you render/project the 3D garment meshes on original video?

**Comment by tomguluson92** [comment]
Thanks for asking, we just use UE5 and Style3D plugin for cloth simulation. The binding process for human and cloth has been automatically done in the UE5 in our project.

Since those part is irrelevant with our core algorithm code, we are not allowed to release those engineer part of codes.
